name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - flagging
          - logging
          - otel
          - utilities
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        working-directory: ${{ matrix.dir }}
        run: go mod download

      - name: Test
        working-directory: ${{ matrix.dir }}
        run: go test -v -coverpkg=./... ./...

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        working-directory: ${{ matrix.dir }}
        run: gosec
        with:
          args: '-no-fail -fmt sarif -out results.sarif ./...'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: ${{ matrix.dir }}/results.sarif
